name: LeetCode → ChatGPT → Notion Sync

on:
  workflow_dispatch:
    inputs:
      limit:
        description: "Number of recent problems to sync"
        required: false
        default: "5"
  schedule:
    - cron: "0 6 * * *"  # daily run at 6 AM UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run sync script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          INPUT_LIMIT: ${{ github.event.inputs.limit }}
        run: python src/sync_leetcode_notion.py
